### ISSUE TITLE
Stuck chests in the air 

### ISSUE THREAD

**Issue by xxxcrow** [Guarmanda/LootChest#13]
Some chests freeze in the air
actuality not chests, but their "particles?"
It stucks around 2 block from the ground
it's impossible to break or "//set air" them 🥲
What to do? 🥺

**Comment by Guarmanda** [comment]
This is an armorstand with a chest on the head. You can remove it with essentials's killall command (/killall armorstand 5) 5 is a radius

**Comment by xxxcrow** [comment]
No fix in the future? Because it's a problem if it would spawn everywhere randomly and just get stuck 🥲

**Comment by xxxcrow** [comment]
Or can i just disable this "chest falling" part, but keep the fireworks part? ☺️

**Comment by Guarmanda** [comment]
That's rare but I can't fix it. Yes you can do this.

**Comment by xxxcrow** [comment]
@Guarmanda rare bug per server or per chest? 😅 because i have a bunch of them, around 5 that i just spotted, and 3 of them in the area where chests spawn every hour (and the server is up just for a week or so)

**Comment by Guarmanda** [comment]
I don't know if the version causes an issue with it, it May depends on chunk loading/unloading, it can depends on many, many factors... I just know it doesn't append on my test server and that I don't know how to reproduce this^^

**Comment by xxxcrow** [comment]
If something, just for statistics, my server is running Yatopia, mc version is 1.16.5, Java 11 (everything is inside a docker container on raspberry pi, but i think it doesn't make any difference)
Thank you anyway for you work and attention 😁
Close the issue please if it's necessary, i mean if there's no point to keep it opened 😅

**Comment by Guarmanda** [comment]
Yeah, maybe I'll be able to fix this in some years x)
