### ISSUE TITLE
Plugin automatically being disabled after loading

### ISSUE THREAD

**Issue by GamerMomB** [Guarmanda/LootChest#16]
I don't know if it is because I am using 1.17. But the Plugin immediately disables after loading when I start up the server. If I try to use any of the commands in game they just issue an internal error. Lots of other 1.16 plugins still work in 1.17, but apparently this one does not?

**Comment by Guarmanda** [comment]
1.17 update will be out on july the 26th, that's why it doesn't work for now, sorry

**Comment by GamerMomB** [comment]
Awesome. Thank you for the quick answer. I look forward to trying it out :)
