### ISSUE TITLE
Console get spammed

### ISSUE THREAD

**Issue by Stormez1998** [Guarmanda/LootChest#22]
Hello,
my MC server is running on 1.12.2 and fine. Everytime whe a chest is unlooted and spawned the console says everysecond that line: [22:02:04] [Server thread/INFO] [fr.black_eyes.lootchest.Main]: [LootChest] Armorstand found (uuid)

i didn´t figure out why.
Thanks for help

**Comment by Guarmanda** [comment]
Everything should be fine now but... try and tell me!

**Comment by Stormez1998** [comment]
Worked thanks :)
