### ISSUE TITLE
NEW interesting Ideas

### ISSUE THREAD

**Issue by yellow-pillow** [Guarmanda/LootChest#23]
Hi, I have a very cool idea for a loot chest, I'm ready to help you implement it if you need

basically i want you to add 2 cool features that can be disabled for those who don't need it
min_players_to_start_event: true
advance_notice: true

Functions:
1)add the ability to start airdrop only if there is the required minimum number of players on the server
(because at night is playing 1-3 people and there is no incentive to rush, there will be no fighting, bored)

2)Add an announcement of airdrop place in advance!
this would gather all the players in this place and allow you to start a battle for airdrop, just think how cool it would be!
(if someone doesn't need it you can turn it off)

EXAMPLE CONFIG:
min_players_to_start_event: true
   - min: 20

advance_notice: true
   - first: 30m
   - second: 15m
   - third: 1m

**Comment by Guarmanda** [comment]
Hello,
I began a big update but didn't finished it yep, it would add all effect of each version to the plugin instead of suporting only multi-version effects.
I didn't finished this yet, even if I'm close to the end, but I'm verry, verry overbooked for now.

**Comment by yellow-pillow** [comment]
I think that updating the effects is useless, I only use fire because it is the brightest, why do you want to add all the effects, what is the point?
Give me an example, maybe I'll understand))

I think the update I suggested you make a lot faster and easier + I would even be willing to buy such a version of the plugin as a premium version, I think other server creators would also like these features

+ I have not found any analogue of your plugin, so I offered this idea only to you

**Comment by yellow-pillow** [comment]
+ I do not fall chest as you have it shown on the page of the plugin, and I would very much like))

**Comment by yellow-pillow** [comment]
+ if you're interested in my vision, I'd like to see a big red cross of particles where the airdrop appears 
(like on the treasure map)

I think this update would be very cool

**Comment by Guarmanda** [comment]
The minimum number of players is now included in the plugin. The chest falling thing was totally recoded too
