### ISSUE TITLE
Version vor 1.18

### ISSUE THREAD

**Issue by sphings79** [Guarmanda/LootChest#24]

**Comment by sphings79** [comment]
Hi,

would be very nice to have your plugin working on 1.18

regards

sphings

**Comment by Guarmanda** [comment]
During Christmas holydays.

**Comment by cmod31** [comment]
supports 1.18 now https://www.spigotmc.org/resources/lootchest.61564/

**Comment by Guarmanda** [comment]
How can you be so fast x)
