### ISSUE TITLE
FEATURE

### ISSUE THREAD

**Issue by Spiderjockey02** [Guarmanda/LootChest#26]
be able to have "presets" of chests. So you could assign, for example, 2 chests the same preset, You then can edit the preset and the 2 chests will update (This will also save a lot on the data.yml file)

**Comment by yellow-pillow** [comment]
why? is 2-3 mb too much for you? the function of copying presets / chests already exists

**Comment by Guarmanda** [comment]
> why? is 2-3 mb too much for you? the function of copying presets / chests already exists

Don't be so mean, he's right in a way, that would be a good feature, many People asks for it

**Comment by yellow-pillow** [comment]
> 

No, I'm not angry, I just wanted to help.)
