### ISSUE TITLE
invisibils statue and chest

### ISSUE THREAD

**Issue by Stormez1998** [Guarmanda/LootChest#27]
Hay me again, thanks for the help. after reinstalling the plugin it worked now with the console spam.

But now sometimes when i arrived at a chest there is a smaller chest on top of the normal chest, when i loot then chest the normal disapears but the invisibile ammorstand will stand there and i cant destroy them. Example before looting the chest:
![2022-01-04_05 45 48](https://user-images.githubusercontent.com/57358176/148010692-7c90fce2-e829-4d8c-87e2-b297e28cbae9.png)
Example after looting the chest:
![2022-01-04_05 46 02](https://user-images.githubusercontent.com/57358176/148010693-3d99b503-f094-47e8-ab43-f03cd8e9736c.png)

best wishes

**Comment by Guarmanda** [comment]
This thing just... Should not append at all O_o can you provide tour server version ?

**Comment by Stormez1998** [comment]
sure.

Server version: Magma 4152130 (1.12.2) Bungeecord
Config:
`CheckForUpdates: true
ConsoleMessages: true
Cooldown_Before_Plugin_Start: 0
Particles:
  enable: true
  default_particle: FLAME
  number: 10
  respawn_ticks: 5
  radius: 0.3
  speed: 0.05
default_reset_time: 10
default_item_chance: 100
use_players_locations_for_randomspawn: false
save_Chest_Locations_At_Every_Spawn: false
UseHologram: true
RemoveEmptyChests: true
Protect_From_Explosions: true
Prevent_Chest_Spawn_In_Protected_Places: false
RemoveChestAfterFirstOpenning: false
Hologram_distance_to_chest: 1
PreventHopperPlacingUnderLootChest: true
Minimum_Number_Of_Players_For_Natural_Spawning: 1
WorldBorder_Check_For_Spawn: true
Destroy_Naturally_Instead_Of_Removing_Chest: true
Radius_Without_Monsters_For_Opening_Chest: 0
Fall_Effect:
  Let_Block_Above_Chest_After_Fall: true
  Optionnal_Color_If_Block_Is_Wool: CYAN
  Block: CHEST
  Height: 75
  Enabled: true
  Enable_Fireworks: true
  Speed: 0.2
Timer_on_hologram:
  Show_Timer_On_Hologram: true
  Hours_Separator: ' hours, '
  Minutes_Separator: ' minutes  and '
  Seconds_Separator: ' seconds'
  Format: '%Hours%Hsep%Minutes%Msep%Seconds%Ssep left for respawn'
respawn_notify:
  bungee_broadcast: false
  per_world_message: false
  message_on_chest_take: true
  natural_respawn:
    enabled: true
    message: '&6A Lootbox dropped &6 \n&6at [x], [y]!'
  respawn_with_command:
    enabled: true
    message: '&6The chest &b[Chest] &6has just respawned \n&6at [x], [y], [z]!'
  respawn_all_with_command:
    enabled: true
    message: '&6All chests where forced to respawn!\n&6Get them guys!'
`

**Comment by Gabo6480** [comment]
Having the same problem, I have multiple unremoveable armor stands around in my map. Tried using the /kill command and a new armor stand replaces it (I know it is a different one since it has a new ID).
They are affected by gravity so I might drop them to the void.

**Comment by Gabo6480** [comment]
They started appearing after I disabled the holos from spawning over the chests. Before it I never had this problem.

**Comment by Guarmanda** [comment]
It seems like removing the holo also removes the block above chest, so disabling holo stops the removing of holo AND the removing of this block. Need to be tested more by myself

**Comment by Guarmanda** [comment]
This is fixed in the code now (for next version) holograms will be using packets instead of entities from now, so there will be no more bugged holograms
