### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by cas22** [Guarmanda/LootChest#31]
Hello, my server is running 1.18.2 (purpur)
And I can't eaven connect to the server
[latest.log](https://github.com/Guarmanda/LootChest/files/8701474/latest.log)

**Comment by Guarmanda** [comment]
I don't really use purpur much... maybe you could try disabling Lootchest's particles in config.yml

**Comment by cas22** [comment]
Right now I'm on a trip, when I get back I will try to do that. It is probably what you have said, the particles, because the issue only happened when there where loot chest(s) programmed, also the server lagged immediately after I created a loot chest.
