### ISSUE TITLE
Application to move "LootChest" to MCBBS

### ISSUE THREAD

**Issue by Annijang** [Guarmanda/LootChest#33]
Hi, can I move "LootChest" to the MCBBS forum? I have added Chinese language for this addon and want to share it with our Chinese Minecraft players, I will point to a link to spigotmc,MCBBS is currently the largest minecraft forum in China.
MCBBS Link：https://www.mcbbs.net/

**Comment by Guarmanda** [comment]
As long as you don't sell it, I don't see any problem
