### ISSUE TITLE
Feature request:Provides a button to delete the hologram and a button to add the number of daily opens

### ISSUE THREAD

**Issue by Annijang** [Guarmanda/LootChest#34]
I want to set up a chest for my server players that each player is only allowed to open once, and I want to add the number of times the chest can be opened per person per day, Because I didn't find a way to delete the hologram in the game, so I came to give you feedback to see if this function is missing.,I don't know if "LootChest" can do this typ.
![PCM%5( HLA58ZBE`{Y$4MNN](https://user-images.githubusercontent.com/75552974/175800139-1024cff1-3230-4c67-8131-263142160c5b.png)

You can add a button to delete the hologram in the ninth position of the second row in the menu:
![T7)JHUMI~5}DFJ8X99U~B2O](https://user-images.githubusercontent.com/75552974/175800161-29afcfa5-b147-41c0-b01c-8b6dac22fe36.png)

**Comment by Guarmanda** [comment]
You can remove an Holo by setting it to "" or " " or "null"
