### ISSUE TITLE
Feature Idea: On respawn command

### ISSUE THREAD

**Issue by Gabo6480** [Guarmanda/LootChest#35]
The title is pretty self explanatory. Just adding a field to add a command that is run when the chest spawns, with some placeholders we can use to fill in the information. 
With this the user could use commands like DiscordSRV's `/discord broadcast <text>` to send a message in their discord server announcing the respawn of the chest.

**Comment by Gabo6480** [comment]
Either that, or you can add a DiscordSRV integration

**Comment by Gabo6480** [comment]
Or you could add a custom event for when a LootChest respawns with all the relevant information, such as the message which is going to be broadcasted. That way we can use the alerts.yml in DiscordSRV to create a custom alert in the discord chat.

**Comment by Guarmanda** [comment]
an event would be a better and easyer idea, yep

**Comment by Guarmanda** [comment]
Custom event added
