### ISSUE TITLE
Important suggestions for plugins!

### ISSUE THREAD

**Issue by DimaSergeew** [Guarmanda/LootChest#37]
1) Make it possible to set a chest opening timer!
2) Make it possible for the chest to protect the territory where it fell! Players often private it
3) Sometimes, after restarting the server, the chest stops randomly falling

**Comment by Guarmanda** [comment]
Restarting the server loads all chests timers, so it should be the oposite: restarting server is a way to debug the chests, so I don't know how such a thing appenned. Opening timer is a feature that was requested many time, so maybe I'll do it

**Comment by Guarmanda** [comment]
I won't protect a whole area for a chest. Opening timer is here now
