### ISSUE TITLE
Support 1.7.10?

### ISSUE THREAD

**Issue by Serega007RU** [Guarmanda/LootChest#39]
Hello! What about 1.7.10 support? Most commands don't work on 1.7.10, the plugin throws errors in the console
Here is the log [2022-09-01-2.log](https://github.com/Guarmanda/LootChest/files/9468905/2022-09-01-2.log)

**Comment by Guarmanda** [comment]
I'll test more 1.7.10 in next version then, thanks for reporting

**Comment by Guarmanda** [comment]
I just updated the plugin.
I tested it successfully on 1.7.5, so it should work too on 1.7.10.

**Comment by Serega007RU** [comment]
Thanks for the support! If there are any problems, we will let you know
