### ISSUE TITLE
making lootchest compatible with itemsAdder

### ISSUE THREAD

**Issue by JunkieCraft** [Guarmanda/LootChest#40]
Hello, I recently installed lootchest and found that it is not compatible with ItemsAdder, if I have lootchest installed, itemsadder does not work properly. 

I have been looking and it may be because lootchest is not compatible with itemsadder, is it possible that in the future this compatibility will be added?

Thanks!

**Comment by Guarmanda** [comment]
It will in next version, sorry for the inconvenience. My plugin protects armorstands too much and wasn't checking it it was LootChests holograms or simple armorstands
