### ISSUE TITLE
Little color parsing issue [low]

### ISSUE THREAD

**Issue by mrfloris** [Guarmanda/LootChest#42]
<img width="769" alt="Screen-Shot 2022-10-10 at 08 05 45" src="https://user-images.githubusercontent.com/28841349/194806689-a3130c47-71f9-4b01-8abd-c28f6c3f7025.png">

/lc edit chestname

then hover over totem to deactivate, once you do that the reactivate shows &6 instead of parsing it. 

Not really a bug, but, though i'd let you know.

**Comment by Guarmanda** [comment]
Fixed in next version, or should be at least. Another problem regarding weird characters in lootchest broadcasts will also be solved.

**Comment by mrfloris** [comment]
Hey, and thank you - that's fantastic to hear.
