### ISSUE TITLE
/lc removeallholo wont remove any duplicated hologram

### ISSUE THREAD

**Issue by coliflor** [Guarmanda/LootChest#43]
**/lc removeallholo** wont remove any duplicated hologram

I have to manually use a command to remove all those bugged holograms, the command in question is the following one and it works:
**/minecraft:kill @e[type=armor_stand,distance=..10]**

_The server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)_

**Comment by Guarmanda** [comment]
Holograms/armorstands are a mess that I can't manage to handle. If someone better than me knows why they doesn't get removed by my code on chest despawning, well... it would be great

**Comment by Guarmanda** [comment]
This is fixed in the code now (for next version) holograms will be using packets instead of entities from now, so there will be no more bugged holograms
