### ISSUE TITLE
Invisible armorstands become locked by lootchest plugin

### ISSUE THREAD

**Issue by mrfloris** [Guarmanda/LootChest#44]
Hey there,

We started to notice a while back that invisible armorstands couldn't be edited with CMI's armorstand feature anymore.

I've just done the tedious steps of trying to figure out why, by removing plugins one by one basically. And it turns out it's caused by lootchest. Or rather, without lootchest on the server: we can edit them again, with lootchest: we can no longer edit it again.

I've done three different restarts and tests on a few different systems, and when we add lootchest jar, the same issue occurs. 

```
> ver
[01:24:21 INFO]: Checking version, please wait...
[01:24:21 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-304 (MC: 1.19.2)
> cmi version
[01:24:25 INFO]: --------------------------------------------------
[01:24:25 INFO]: CMI: 9.3.0.2
[01:24:25 INFO]: CMILib: 1.2.4.1
[01:24:25 INFO]: Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
[01:24:25 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[01:24:25 INFO]: Modules -> 55 enabled 2 disabled: flightCharge, votifier
[01:24:25 INFO]: --------------------------------------------------
>
```
And we're using `LootChest 2.3.3`

Some older version of lootchest we had during Halloween, we were not having this problem, so it might be one of the more recent changes perhaps?

Attached you see me try without lootbox installed, then making sure the jar is there, starting it up, trying again, I can't interact, break, or edit the armorstands, and when I /stop and remove lootbox again and start up, I can interact with armorstads again.

If you need more information, feel free to ask, I am not sure what else to ask. 

Oh, yes, there are no console errors when we interact. And interaction being left click as well as right click or sneak right click. 

https://user-images.githubusercontent.com/28841349/208271334-4fc41d6c-e95f-4a79-92d0-a5c0e1ee2c19.mp4

**Comment by Guarmanda** [comment]
This problem has been reported before, and I just found that it's totally true, some days ago, when I started agaoin to work on lootchest. It will be solved in next version.

**Comment by mrfloris** [comment]
Happy new year! And thank you, hopefully it's something you can resolve so we can return the plugin to our server for awesome 2023 events :)

**Comment by Guarmanda** [comment]
Can you confirm if this update fixes compatibility with itemadder? It's on spigot since some minutes.

**Comment by mrfloris** [comment]
Players are reporting they can edit the armorstands, so I think it's all good
