### ISSUE TITLE
Lack of specified function

### ISSUE THREAD

**Issue by liquidman228** [Guarmanda/LootChest#45]
Hey there
I noticed that in description on spigotmc there is a command to set chest protection time, but it is not in the game

![image](https://user-images.githubusercontent.com/93479046/219904593-b8307a1f-4d21-4ffd-a781-e6d5fdb07eda.png)
![image](https://user-images.githubusercontent.com/93479046/219904697-7b87f9aa-1da4-4dea-86d6-5ccb064af760.png)

**Comment by Guarmanda** [comment]
This sets the respawn Time, not the protection time

**Comment by liquidman228** [comment]
Anyways it will be awesome to have that feature
For example, it will force players to fight for chests before opening

**Comment by Guarmanda** [comment]
I confirm that this feature exists, but  that I forgot to add it to autocompletion, but if you type the command it should work (on latest lootchest version only)

**Comment by liquidman228** [comment]
Hmm, when i try to use it, it returns as default list of commands. Even checked the chest, there is no protection
![image](https://user-images.githubusercontent.com/93479046/219956529-607bed64-2a4d-434d-a7ab-2f7ae198dc44.png)

**Comment by Guarmanda** [comment]
tested and working
