### ISSUE TITLE
Automatic chest update does not work

### ISSUE THREAD

**Issue by ghost** [Guarmanda/LootChest#47]
Hi, I want to make a chest and have it automatically updated every hour. I put 1 minute for the test. When I take all the things from the chest, things are not updated. What could be the problem?

**Comment by Swiftform** [comment]
I have the exact same problem.

**Comment by Guarmanda** [comment]
I know this problem but can't reproduce it myself. Last update will may solve this

**Comment by Guarmanda** [comment]
is this still appening?

**Comment by Swiftform** [comment]
> is this still appening?

I don't know, haven't installed the plugin for a while because of this bug. Is it fixed?

**Comment by Guarmanda** [comment]
Well, maybe^^ I found something that could solve the problem and I fixed it, but I'm not certain that it was the problem. For me the plugin works fine. That's why I'm asking
