### ISSUE TITLE
Updating the data.yml and doing /lc reload wipes changes

### ISSUE THREAD

**Issue by TomLewis** [Guarmanda/LootChest#53]
We need the ability to manage the data not in-game using an editor, to move data between servers live, without a reboot.
Theres an issue where if you edit the data.yml and do a /lc reload, it just wipes it back to what it was before.

Can these be fixed as a priority please.

**Comment by Guarmanda** [comment]
If you want to edit the data file, the plugin (or the server) has to be stopped. Let's explain:
- when the plugin starts, it loads datas from the file
- when it stops, it saves the data, because it has to do so on server stop, so that we don't lose chest editions or creations.
- when it reloads, it saves then load the data, so if you edit file during server being started, you will lose your changes

**Comment by TomLewis** [comment]
Oh yeah I gathered, the reload command should re-pull the data.

Let me give you is few reasons.

- development with multiple staff, using a creative server and copying data to a prod server, needs to happen live.
- finding issues, being able to quickly edit a change and reload without a full restart on prod.
- mass editing with a big replace to quickly make changes across all items without a restart for quick testing and also the downtime of prod


It's common practice across most plugins to allow this sort of behaviour from an moderation and admin perspective, hopefully we can get the same updated with this!

**Comment by Guarmanda** [comment]
This will probably lead to a new line in the config
"SaveDataFileDuringReload"

**Comment by TomLewis** [comment]
@Guarmanda bit of a issue, can't even reboot and put over new data, it must overwrite it when the server shuts down on a reboot 😕

**Comment by Guarmanda** [comment]
yes it does: the data file is saved on shutdown, so you can only replace it when server is completelly off
I'll add that config line anyway

**Comment by Guarmanda** [comment]
Done

**Comment by TomLewis** [comment]
Nice 👍
