### ISSUE TITLE
Timers not working on our survival

### ISSUE THREAD

**Issue by TomLewis** [Guarmanda/LootChest#55]
Oddly the timers are not working on our survival server, but they work on our creative server (I will have to check, im not running this event) I dont see any errors in the console from the plugin, is it better to not use the built in scheudle system and run it instead from the wrapper cron fireing manual commands to spawn?

Any other ideas at why/how the timers would not work from the in-game GUI?

**Comment by Guarmanda** [comment]
It is may due to a limit of player for chests to respawn, in config. If you set a limit of player, it breaks respawn. I will be fixed in next version

**Comment by Guarmanda** [comment]
does it still apens?

**Comment by Guarmanda** [comment]
Not any responses

**Comment by TomLewis** [comment]
Yea I use limits of players for a respawn I think

**Comment by Guarmanda** [comment]
It should be fixed, that's why I asked if it still appends
