### ISSUE TITLE
[suggestion]Support MMOitems random stats

### ISSUE THREAD

**Issue by minecraft-dripdrop** [Guarmanda/LootChest#57]
mmoitems weapon have random attack-damage and other random things
Can you support it?

https://gitlab.com/phoenix-dvpmt/mmoitems/-/wikis/Item-Stats-and-Options

**Comment by Guarmanda** [comment]
Have you tested the plugin as is before asking for this :D ? My plugin even works with modded items. I don't edit items at all, I let spigot saving them itself, so mmoitems have a good chance to work without any modification
