### ISSUE TITLE
2.4.0 still does not reload data.yml when /lc reload

### ISSUE THREAD

**Issue by TomLewis** [Guarmanda/LootChest#58]
Any modifications to the data.yml live then running /lc reload, just overwrites the data with whatever is loaded into memory.
Even if I delete the data.yml and run /lc reload it just pops it back from whatever state it booted up as at server boot.

Really bad for production servers. and building things on a test server to move over.

**Comment by Guarmanda** [comment]
There is a config option for this: SaveDataFileDuringReload
