### ISSUE TITLE
Hologram on 1.20.4 shows too low, making it dark

### ISSUE THREAD

**Issue by mrfloris** [Guarmanda/LootChest#59]
The light level of holograms is wrong due to the hologram being a bit too low.
This doesn't always seem to happen on all the chests, but it happens, and in 1.20.4, it happens a lot more.

<img width="686" alt="Screenshot 2024-04-10 at 09 09 21" src="https://github.com/Guarmanda/LootChest/assets/28841349/58d14d05-f3cd-49a3-aec1-0b9093da38ad">

<img width="1574" alt="Screenshot 2024-04-10 at 09 07 44" src="https://github.com/Guarmanda/LootChest/assets/28841349/50df8db6-bf71-4dd0-a56c-bfe51f51031f">

We are using CMI with CMI hologram (9.7.0.x) if that makes a difference.
[data.yml.zip](https://github.com/Guarmanda/LootChest/files/14928767/data.yml.zip)

No startup, shutdown or usage errors in latest.log, if you have any questions, feel free to let me know. 
You can check how it looks at 1moreblock.com at /warp charlie, once they are loaded (mrfloris, I can help with that)

**Comment by Guarmanda** [comment]
This config line could solve your problem:
Hologram_distance_to_chest: 1

I'll may add 0.2 tu that number for further versions

**Comment by Guarmanda** [comment]
I'll also add that lootchest doesn't connect to any plugin to make holograms, it uses an api compatible from 1.8 to 1.20, because I don't want it to depend on anything. Using a server's hologram plugin would makes too much different behaviors, like if you use a plugin or another, how you configured your hologram plugin, if the plugin really works or not with your server version...

**Comment by mrfloris** [comment]
> This config line could solve your problem: Hologram_distance_to_chest: 1
> 
> I'll may add 0.2 to that number for future versions

Och, that's an oversight on my part that I could have played with. Thank you for the help. I will try some stuff out.



> I'll also add that lootchest doesn't connect to any plugin to make holograms, it uses an api compatible from 1.8 to 1.20, because I don't want it to depend on anything. Using a server's hologram plugin would makes too much different behaviors, like if you use a plugin or another, how you configured your hologram plugin, if the plugin really works or not with your server version... It would be too much complicated for me to debug/maintain

100% fine by me! Makes updating to 1.20.5 a lot smoother.

**Comment by mrfloris** [comment]
> This config line could solve your problem: Hologram_distance_to_chest: 1
> 
> I'll may add 0.2 to that number for future versions

I had time to play around 1.2 is a fine setting.

**Comment by Guarmanda** [comment]
> 100% fine by me! Makes updating to 1.20.5 a lot smoother.

My plugin still depends on protocollib because of this API, and it seems like it doesn't work in 1.20.5 sadly^^

**Comment by mrfloris** [comment]
> > 100% fine by me! Makes updating to 1.20.5 a lot smoother.
> 
> My plugin still depends on protocollib because of this API, and it seems like it doesn't work in 1.20.5 sadly^^

There's a WIP release of PL for 1.20.5/6
https://ci.dmulloy2.net/job/ProtocolLib/changes

**Comment by Guarmanda** [comment]
My plugin will use a new library for holograms and won't have protocollib requirements anymore

**Comment by Guarmanda** [comment]
The push was made for the library already, holograms are slightly higher, I'll close this issue
