### ISSUE TITLE
Lootchest and Hologram not despawning after being claimed

### ISSUE THREAD

**Issue by binhxlore** [Guarmanda/LootChest#6]
How to replicate:
-- Create a random spawn lootchest
-- /lc tp to chest to test out the claim
-- Open chest and gather all its contents
-- Chest and hologram did not despawn

**Comment by binhxlore** [comment]
I would like to mention that when destroying the chest, the hologram still stays and there is no way to remove the text.  This is really frustrating since the chest spawns in people's homes and the texts never go away!

**Comment by Guarmanda** [comment]
You can remove them by sitting next to them and doing this essentials's command:
/killall named 5 (5 is a radius)
This bug shouldn't even append but I'll fix this in next update by sending packets father than spawning entities

**Comment by binhxlore** [comment]
So I have found another glitch.  When a chest creates a firework explosion,
a bugged chest is created at the explosion site.  There are now hundreds of
bugged chest in my world.  Is there a command that would target only these
chests and not regular armor stands or named entities?

The following command works to get rid of all armorstands: /minecraft:kill
@e[type=minecraft:armor_stand,distance=..5]

But I am trying to get rid of *only *the invisible ones and the following
commands does not work:
 /minecraft:kill
@e[type=minecraft:armor_stand,distance=..5,nbt={invisible=1}]
/minecraft:kill
@e[type=minecraft:armor_stand,distance=..5,nbt={invisible=0}]
/minecraft:kill
@e[type=minecraft:armor_stand,distance=..5,nbt={invisible=1,invulnerable:1}]
<-- any combination of this
/minecraft:kill
@e[type=minecraft:armor_stand,distance=..5,nbt={invulnerable=1}]

**Comment by binhxlore** [comment]
Also the command you gave me :  /killall named 5
Does not work. Just FYI.

**Comment by binhxlore** [comment]
I have found another issue.  I have about 100 random chests spawned around the world and they respawn every 30 minutes.  Every 30 minutes, the TPS drops from 20 to 13, always corresponding with the chest respawns.  D:  I had to remove this plugin since there were too many issues.

**Comment by Guarmanda** [comment]
these bugs are weird, I mean I don't get them plus everything is saved everytime so armorstands should disapear correctly :/ For the TPS drops, you can disable the "save at each spawn" option (or something like that) It saves the data folder at each spawn to prevent data loses on crash, but it can cause lags with many many chests

**Comment by Guarmanda** [comment]
This is fixed in the code now (for next version) holograms will be using packets instead of entities from now, so there will be no more bugged holograms
