### ISSUE TITLE
[LootChest] Task #121/122/123/124 for LootChest v2.1.1 generated an exception

### ISSUE THREAD

**Issue by iDeniable** [Guarmanda/LootChest#7]
I am on server version 1.16.1 

https://pastebin.com/TH52hmfA

**Comment by crashmaker18** [comment]
I've got the same thing happening.
It doesn't matter if it tries to paste into the actual worldguard region or not. Disabling "Prevent_Chest_Spawn_In_Protected_Places: true" 'fixes' it, but then it spawns in regions where players can't even open chests.
It doesn't happen one a server that doesn't have worldguard installed. Worldguard is also on the latest version.
https://pastebin.com/RSqu1k5T

**Comment by Guarmanda** [comment]
Mmmh yeah, worldguard changes it's code often, I'll see this before updating my plugin

**Comment by Guarmanda** [comment]
Fixed in last update
