### ISSUE TITLE
Proposal to implement a chest UI System for easier menu management

### ISSUE THREAD

**Issue by GorgeousOne** [Guarmanda/LootChest#76]
Okay, so I might have taken a little peek at the menu system too 😄, and I noticed everything is handled in two mega classes. I thought it’d be cool to give it a modular makeover as well!

I’d like to propose refactoring the system with a dedicated ChestUi class. This would allow predefined logic for interactions with inventory UI items, eliminating the need to manually check which UI a player is interacting with or using long switch blocks for all slots.

Proposed System:

ChestUi Class:
- This class would serve as a base for individual menus (similar to how `SubCommand` works). It would provide an inventory where items can be set and actions bound to specific slots.
- When a slot is clicked, the respective action will be triggered automatically.

UiHandler Class:
- This class would listen for player interactions and delegate click events to the correct `ChestUi` instance based on the player's open inventory.

With this approach, each menu would have its own class again, but in a more streamlined and maintainable way.
Let me know if you're interested, I’d be happy to make a pull request!

Looking forward to your feedback.

**Comment by Guarmanda** [comment]
Well... This could lead to many new bugs and these menus are really rarelly modified but... If you manage to get this work, it would help people understand the code in the future^^

**Comment by Guarmanda** [comment]
You're mad bro :D

**Comment by Guarmanda** [comment]
You added really few lines because of the improvements you made to my old code, it's even better than your commands rework^^ Thank you so much, you may also have solved some bugs, who knows

**Comment by GorgeousOne** [comment]
Glad you like the changes :D It was a bit more fun than the commands, too. Maybe I'm crazy, but I think I just enjoy sorting stuff a bit :p But I also think Lootchest is definitely a cool plugin. 
Good luck and have fun developing it in the future!
![](https://y.yarn.co/9384c2c5-9e85-4414-906a-b3be25ce13dc_text.gif)
![](https://y.yarn.co/df8d2234-dc38-4edc-82bd-c8c7b7399f9a_text.gif)
