### ISSUE TITLE
Lootchests rudiments

### ISSUE THREAD

**Issue by Submons** [Guarmanda/LootChest#82]
I have the problem that I often find unclaimed lootchests in my world. (Chests without a hologram but with the contents of the lootchests)

Can the cause be restarting the server or is it a known bug?

THX

MC 1.21.1
LC  2.4.6

**Comment by Guarmanda** [comment]
When you restart, the Holo should be recreated 🤔 and it isn't a known bug but it may be a bug anyway
Maybe I should test this more

Le 1 nov. 2024, 16:25, à 16:25, Submons ***@***.***> a écrit:

**Comment by Guarmanda** [comment]
When you restart, the Holo should be recreated 🤔 and it isn't a known bug but it may be a bug anyway

Maybe I should test this more

**Comment by Submons** [comment]
Oh, I see that 2.4.6 failed to install properly... I'm investigating..

https://pastebin.com/uCpDJRfe

**Comment by Guarmanda** [comment]
Saddly i'm not at home this week end^^
Error with metrics?! Wtf?!

**Comment by Submons** [comment]
After removing Welcomer_plus 2.6.6, Lootchest 2.4.6 could be activated. I'll check if the error still occurs after restarts

**Comment by Submons** [comment]
Update - More details about my problem:

The chests only appear (remain standing) after a server restart, but unfortunately not after every restart. It is also not possible to adjust whether it is triggered by an automatic restart or a manual one. 

The brocken chests are in different positions every day

The positions of the remaining chests are not in the backups *data.yml under randomPosition

Setting save_Chest_Locations_At_Every_Spawn to true didn't work

MC 1.21.1
LC 2.4.6

**Comment by Guarmanda** [comment]
This is now fixed. The standing chests that you still have on your servers are armorstands and mayb can be removed with a command like /killall
The new falling chests are now packets, so if they bug, they will disapear after you disconnect/reconnect.
