### ISSUE TITLE
Pitch Yaw and Direction

### ISSUE THREAD

**Issue by IDiedTryin** [Guarmanda/LootChest#88]
Barrels always face north.
Pitch and yaw don't seem to do anything.
Chests can be changed to point different direction after editing the data.yml file.
after any editing of the data.yml the chests stop respawning until a /lootchest:reload or /lootchest respawn(all) is run.

sidenote: Typo's in the config.yml

EnableLootin: false

 Some people have troubles about worlds loading before my plugin: in fact, chests located in unloaded worlds aren't loaded.
** Let's fi this with this option. Cooldown is in second.**

What is trying to said in the last line?

 removes the chest when a player closes it, even if there's still items in it
**RemoveChestAfterFirstOpenning: false**

**Opening** is the correct spelling, which you have correctly spelled further down.

Fall_Effect:
   this option is for versions before 1.13: since 1.13, we have **diferent** material for each wool color, so we don't need this.
   Colors are wrong, for example, PINK is CYAN and CYAN is PINK. Spigot bug, sorry.
  **Optionnal_Color_If_Block_Is_Wool**: CYAN

**different**
**Optional**

Thanks for the updating the plugin, hope all is well.

**Comment by Guarmanda** [comment]
The last option is not supported anymore, so I simply deleted it. The other things are fixed in
