### ISSUE TITLE
Chests that drop around player locations are completely broken

### ISSUE THREAD

**Issue by brandonbunce** [Guarmanda/LootChest#9]
Hey sorry to keep bothering you but when _use_players_locations_for_randomspawn: true_ the chests that it's dropping are really broken.

The chests are spawning with all the right loot, but when it is emptied, it does not disappear or announce it was emptied.
Additionally, the holograms are off to the side and are not despawning no matter what.
![2020-11-18_10 01 12](https://user-images.githubusercontent.com/67491262/99569384-682b7600-2985-11eb-8e9c-7588be129867.png)

**Comment by Guarmanda** [comment]
I just tested this feature on 1.16.4, I'd like to know what server version you're using, and if you're using last plugin version

**Comment by Guarmanda** [comment]
thanks this is now fixed
